### ISSUE TITLE
Sorting Algo

### ISSUE THREAD

**Issue by faizm10** [faizm10/cis2520-exam-review#10]
### Task List for Visual Examples of Sorting Algorithms

- [ ] Add visual example for **Bubble Sort**
- [ ] Add visual example for **Insertion Sort**
- [ ] Add visual example for **Quick Sort**
- [ ] Add a better visual example with description for **Selection Sort**
- [ ] Review and ensure all visual examples are clear and well-labeled
- [ ] Include references for the visual sources (if applicable)

**Comment by kaarishp** [comment]
<img width="603" alt="bubblesort" src="https://github.com/user-attachments/assets/c60b3d2d-64e6-43f0-9c78-fc8c0ed523b3">
